# Generated by Django 3.2.16 on 2022-11-14 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_auto_20221104_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='costumer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='costumer', to='auth.user'),
            preserve_default=False,
        ),
    ]
