# Generated by Django 3.2.16 on 2022-11-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_costumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='costumer',
            field=models.CharField(max_length=80),
        ),
    ]
