# Generated by Django 3.2.16 on 2022-11-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20221116_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='costumer',
            field=models.CharField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
