# Generated by Django 3.2.16 on 2022-11-16 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20221116_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='flavor',
            field=models.IntegerField(choices=[(0, 'Chocolate'), (1, 'Cocconut'), (2, 'White Chocolate'), (3, 'Pistach'), (4, 'Peanut')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.IntegerField(choices=[(0, 'Small - 4 un.'), (1, 'Medium - 6 un.'), (2, 'Large - 10 un.')], default=0),
        ),
    ]
