# Generated by Django 3.2.16 on 2022-11-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20221116_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.IntegerField(choices=[(0, 'S - 4 un. / $5,00'), (1, 'M - 6 un. / $7,00'), (2, 'L - 10 un. / $10,00')], default=0),
        ),
    ]
