# Generated by Django 3.2.16 on 2022-11-25 21:03

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20221125_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pick_up',
            field=models.DateField(validators=[order.models.validate_date]),
        ),
    ]
