# Generated by Django 3.2.16 on 2022-11-26 16:48

from django.db import migrations, models
import order.models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_alter_order_pick_up'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pick_up',
            field=models.DateField(validators=[order.models.validate_date]),
        ),
    ]
